### ISSUE TITLE
java.lang.IllegalArgumentException: Could not find field with name method during startup

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#88]
When running the jfr-daemon in a docker container with the Java version `ubuntu-1804-java:11.0.6`

This error is because we are looking up a field with `name` when it doesn't exist. To avoid the stack trace, lets check for the existence of the field before getting it.  

```
2020-10-01T18:22:32,850+0000 [7 43] com.newrelic INFO: JMX LinkingMetadata: Fetching linking metadata from the agent...
18:22:32.854 [pool-2-thread-1] INFO  com.newrelic.jfr.daemon.lifecycle.RemoteEntityGuidCheck - Entity guid obtained from remote: MTAxMDU0NTd8QVBNfEFQUExJQ0FUSU9OfDI1MDI4MjAy
2020-10-01T18:22:33,104+0000 [7 36] com.newrelic INFO: Real user monitoring is enabled for application local_flame_traceAsEvent_endpoint. Auto instrumentation is enabled.
18:22:34.160 [JFRController] ERROR com.newrelic.jfr.daemon.EventConverter - Dropping event jdk.CompilationFailure null due to error
java.lang.IllegalArgumentException: Could not find field with name method
        at jdk.jfr.consumer.RecordedObject.getValue(RecordedObject.java:227) ~[?:?]
        at jdk.jfr.consumer.RecordedObject.getValue(RecordedObject.java:168) ~[?:?]
        at com.newrelic.jfr.toevent.JITCompilationMapper.apply(JITCompilationMapper.java:38) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at com.newrelic.jfr.toevent.JITCompilationMapper.apply(JITCompilationMapper.java:30) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at com.newrelic.jfr.daemon.EventConverter.lambda$convertAndBuffer$5(EventConverter.java:77) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.newrelic.jfr.daemon.EventConverter.convertAndBuffer(EventConverter.java:78) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at com.newrelic.jfr.daemon.EventConverter.lambda$convert$0(EventConverter.java:46) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.newrelic.jfr.daemon.EventConverter.convert(EventConverter.java:46) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at com.newrelic.jfr.daemon.JFRUploader.maybeDrainAndSend(JFRUploader.java:76) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at com.newrelic.jfr.daemon.JFRUploader.handleFile(JFRUploader.java:55) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at com.newrelic.jfr.daemon.JFRController.lambda$loop$1(JFRController.java:72) ~[jfr-daemon-0.5.0.jar:0.5.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by XiXiaPdx** [comment]
It's been a while and trying to repro and investigate. I have not been able to repro with a dockerized sample app.

**Comment by kittylyst** [comment]
@XiXiaPdx This is already fixed by https://github.com/newrelic/newrelic-jfr-core/pull/112
